vim.g.airline_theme = "violet"
vim.g.airline_statusline_ontop = 0
vim.g.airline_powerline_fonts = 1
vim.g.airline_left_sep=''
vim.g.airline_right_sep=''
vim.g.airline_mode_map = {
       ['__']  = '-',
       ['c']  = 'C',
       ['i']  = 'I',
       ['ic']  = 'I',
       ['ix']  = 'I',
       ['n']  = 'N',
       ['multi']  = 'M',
       ['ni']  = 'N',
       ['no']  = 'N',
       ['R']  = 'R',
       ['Rv']  = 'R',
       ['s']  = 'S',
       ['S']  = 'S',
       ['']  = 'S',
       ['t']  = 'T',
       ['v']  = 'V',
       ['V']  = 'V',
       ['']  = 'V',
       }

vim.g["airline#extensions#tabline#enabled"] = 1
vim.g["airline#extensions#tabline#show_buffers"] = 1
vim.g["airline#extensions#tabline#buffer_min_count"] = 0
vim.g["airline#extensions#tabline#formatter"] = 'unique_tail'
